config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  #requires a name in order to create a Pet
  validates :name, presence: true
  validates :name, length: { minimum: 5 }
  #validation for the species to be include in a group of species
  validates :species, inclusion: { in: %w(dog cat peacock snake turtle) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show,:edit,:update,:destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
     redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end


  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name,:age,:species,:found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets382</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
<%= f.input :name %>
<%= f.input :species, collection: %w(dog cat peacock snake turtle) %>
<%= f.input :age %>
<%= f.input :found_on, as: :date %>
<%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Pets</h1>
<ul>
 <% @pets.each do |pet| %>
  <li><%= link_to pet.name, pet_path(pet) %> - <%= pet.species.capitalize %></li>
 <% end %>
</ul>

<%= link_to "Add new Pet", new_pet_path %>

app/views/pets/new.html.erb
<h1>Add a New Pet</h1>

<%= render 'form' %>

app/views/pets/show.html.erb
<h1 class="font-color">Show Page</h1>

<h2><%= @pet.name %></h2>

<p>Species: <%= @pet.species.capitalize %></p>
<p>Age: <%= @pet.age %></p>
<p>Found On: <%= @pet.found_on %></p>

<%= link_to pets_path do %>
  <i class="fas fa-backward"></i>
<% end %>
<%= link_to edit_pet_path(@pet) do %>
 <i class="far fa-edit"></i>
<% end %>
<%= link_to pet_path(@pet), method: :delete, data: {confirm: "Are you sure?"} do %>
  <i class="fas fa-dumpster"></i>
  <!-- becomes a link -->
<% end %>